version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookly_user -d bookly_db"]
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: bookly_redis
    restart: always
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bookly_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --log-config=src/log_conf.yml

volumes:
  postgres_data:
  redis_data:
