version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookly_user -d bookly_db"]
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: bookly_redis
    restart: always
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bookly_celery
    restart: always
    env_file:
      - ../.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ../src:/app/src
    command: celery -A src.celery_tasks worker --loglevel=info --hostname=worker1@%h

  flower:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bookly_flower
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - ../.env
    depends_on:
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_started
    volumes:
      - flower_data:/app/flower
    # Flower monitoring tool configuration:
    # - Connects to Redis broker for task monitoring
    # - Exposes web interface on port 5555
    # - Enables real-time task events
    # - Uses persistent storage for monitoring data
    # - Secures web interface with basic auth
    command: celery -A src.celery_tasks flower \
        --broker=${REDIS_URL} \
        --port=5555 \
        --inspect_timeout=10000 \
        --enable_events \
        --worker_hostname=worker1@%h \
        --persistent=True \
        --db=/app/flower/flower.db \
        --basic_auth=admin:admin \
        --url_prefix=flower

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bookly_migration
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    command: alembic upgrade head

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bookly_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    volumes:
      - ../src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --log-config=src/log_conf.yml

volumes:
  postgres_data:
  redis_data:
  flower_data:
