"""add role to users table

Revision ID: b29f73cd132b
Revises: b4d1457ba09c
Create Date: 2025-04-01 10:37:06.807263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # NEW


# revision identifiers, used by Alembic.
revision: str = 'b29f73cd132b'
down_revision: Union[str, None] = 'b4d1457ba09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
